modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="sapphiremc"
version="0.5"
displayName="SapphireMC"
credits="Developed by ShadowHolder/AGudMineman (Me!), textures provided by KingPenguin"
displayURL="https://github.com/RolandWH/SapphireMC/"
logoFile="logo.png"
authors="AGudMineman"
description='''
A mod that adds a whole bunch of sapphire related things in minecraft!
'''

[[dependencies.sapphiremc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.sapphiremc]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0]"
    ordering="NONE"
    side="BOTH"
